dist: xenial
language: python
python: 3.6
sudo: false
cache: pip
install:
  - pip3 install -e .
  - pip3 install pdoc3
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script: python -c "import dimdrop.layers as test"
deploy:
  provider: pages
  local-dir: html/dimdrop
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
