language: python
cache: pip
script: python -c '0==0' # Only if script succeeds we can deploy
deploy:
  provider: pages
  local-dir: html/dimdrop
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
