dist: xenial
sudo: true
language: python
python: 3.7
cache: pip
install:
  - sudo pip install .
  - pip install pdoc3
script: pdoc dimdrop --html
deploy:
  provider: pages
  local-dir: html/dimdrop
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
